### ISSUE TITLE
Agate JSON error when navigating Mica's home page once (Cookie related)

### ISSUE THREAD

**Issue by vincentsirois** [obiba/agate#289]
Hi! Agate seems to store a cookie called NG_TRANSLATE_LANG_KEY, which by the name seems like a cookie generated by Angular but I may be wrong.

When I delete all my cache and cookies and I go to my agate web page, the cookie looks like this.
NG_TRANSLATE_LANG_KEY:"%22en%22"

If I go to the Opal web page, the cookie remain unchanged, however if I go to the Mica2 web page the cookie change for:
NG_TRANSLATE_LANG_KEY:"en"

If I then go back on the Agate webpage, all the variables used for dual data bindings in angular show up unchanged and I get this error in the console.
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data [Learn More]
The error show "en" as an error.

If I delete the cookie and I refresh the page, the cookie go back to the original value and everything work again.

**Comment by meek0** [comment]
The angularjs version for the latest released Mica (3.3.1) is 1.6.9 while that of Agate (1.3.1) is 1.5.8. The next 1.4.0 release is to be updated with angularjs 1.6.9.
