### ISSUE TITLE
Cleanups and remaining bugfixes

### ISSUE THREAD

**Issue by kazoompa** [obiba/agate#327]
- [x] Remove the word Agate from AgateRealm enum
- [x] Rename **JDBC Realm** to **SQL Database Realm**
- [x] Added more help text for Realm forms
- [x] Add salt for hashed passwords (JDBC Realm)

**Comment by ymarcon** [comment]
The hashing of user passwords in the SQL database is not handled by the JDBC Realm configuration. What is missing in the form is:

* the Salt style: NO_SALT, COLUMN, EXTERNAL
* when the salt style is:
  * NO_SALT : no additional fields (just like today)
  * COLUMN : help text / field placeholder must specify that the query must return the password and the salt like in `select password, password_salt from users where username = ?`
  * EXTERNAL : either use the username as the salt or allow specifying a string
