### ISSUE TITLE
Validate user existence in LDAP/ActiveDirectory/SQL DB realms during signup

### ISSUE THREAD

**Issue by kazoompa** [obiba/agate#334]
When a external realm user signs up in Agate, an authentication is required to validate the user.
Add a password field to the sign up form.

**Comment by meek0** [comment]
Tentative solution:

- user navigates to signup page
- user selects realm to be used
- if realm is neither the agate-user-realm nor an oidc realm, open a popup
- user enters credentials and submits
- server needs to authenticate user using the provided realm and credentials (create a temp realm and authenticate?)
- if successful, based on #336, return as much info as possible to fill in the form. Else return an error message.
