### ISSUE TITLE
Test Drupal and Agate sign up

### ISSUE THREAD

**Issue by sofiyad** [obiba/agate#345]
![agate1](https://user-images.githubusercontent.com/51130016/59060636-870c7a00-886f-11e9-9ecc-d96a173718cc.png)
Test Drupal and Agate sign up

**Comment by ymarcon** [comment]
After signup with, the form is properly filled but there is also this warning message:
 
```
Warning: json_decode() expects parameter 1 to be string, array given in obiba_mica_app_angular_get_angular_translation() (line 263 of /home/yannick/projects/mica-drupal7/obiba_mica_app_angular/obiba_mica_app_angular.module).
```
