### ISSUE TITLE
agate openid redirect to http instead https

### ISSUE THREAD

**Issue by tdemalliard** [obiba/agate#358]
**Describe the bug**
Behind a reverse proxy (trafficserver version 5.3), agate redirect client to http url which is forbidden.

**To Reproduce**
1. Set up agate behind a reverse proxy
2. goto https://agate.cartagene.qc.ca/ws/oauth2/authorize?client_id=testing&redirect_uri=http%3A%2F%2Fcrhsj104588%3A9090%2Fauth&response_type=code&scope=openid+email+profile&state=XszGeriqyRTmgqnYyylR59y329OeefO3
4. it redirect client to http://agate.cartagene.qc.ca/#/authorize?client_id=testing&redirect_uri=http%3A%2F%2Fcrhsj104588%3A9090%2Fauth&response_type=code&scope=openid+email+profile&state=XszGeriqyRTmgqnYyylR59y329OeefO3

**Expected behavior**
The redirect stay on https. This url is working as expected when replacing url for https

**Screenshots**
![image](https://user-images.githubusercontent.com/3911087/59948236-73e7d580-943d-11e9-9a75-31fb133d7f63.png)

**Desktop (please complete the following information):**
 - trafficserver 5.3 on centos 7.6
 - agate 1.4.6
 - testing openid with 
      - vouch-proxy https://github.com/vouch/vouch-proxy
      - nginx : will display the page protected by openid agate via vouch-proxy

**Smartphone (please complete the following information):**

**Additional context**
If needed, I have docker commands and config files for vouvh-proxy and nginx

**Comment by ymarcon** [comment]
Agate 1.5 will make the OpenID Connect integration easier by providing a discovery URL, as an example:
https://agate-nightly.maelstrom-research.org/.well-known/openid-configuration

Could you try this with the `snapshot` tag of agate's docker?

**Comment by tdemalliard** [comment]
For now, I could make it work with snapshot, but using http instead of https.

**Comment by ymarcon** [comment]
Oauth redirect to authz page is using the public URL (when defined) or the https host:port from config file.
