### ISSUE TITLE
Test Drupal and Agate Signin

### ISSUE THREAD

**Issue by ymarcon** [obiba/agate#385]
Test OIDC signin through Agate from Drupal.

**Comment by ymarcon** [comment]
Current status:
* signup and signin works for Agate
* signup works and signin does not work for Drupal

**Comment by meek0** [comment]
sign in might not work for drupal if the `application`'s redirect url is not set in agate. it must be set as a pattern that matches the one set in keycloak.

**Comment by ymarcon** [comment]
1. drupal application has a redirect url defined in agate
2. keycloak responds/redirects to agate (which itself redirects to drupal see [signin swimlanes](https://drive.google.com/file/d/1zG43U1WZefoQR4odnSgm0QhPRPh53aBl/view?usp=sharing)), so it is not necessary for keycloak to be aware of drupal

**Comment by meek0** [comment]
the application's redirect url property is used by agate to test whether or not it should create the obibasid or not. In keycloak, this uri must be in its `valid redirect urls`.

**Comment by ymarcon** [comment]
Not clear: which application are you talking about? Why is it not working in the case I described? Please provide a steps to foolow to configure properly agate, druapl and the oidc provider.

**Comment by meek0** [comment]
- in agate, as an agate-administrator
- navigate to `Applications`
- edit `drupal`'s application
- if you are testing in localhost: set the `Redirect URI` property to `http://localhost/drupal`
- similarly for mica, its redirect property would be `http://localhost:8082`

it's true that keycloak would not really need to know these considering that it will always (in agate's case) redirect to agate and agate will (through the callback filter) redirect to the right application.

Problem is we tied it to agate's application config. We could also always assume that a user connecting via oidc would always need an obibasid cookie (with its ticket of course) and that could simplify the process.

**Comment by ymarcon** [comment]
It still does not work and the debugger says when signin from mica interface that the obiba ticket is not valid (because mica app is not one of the audience claim, TokenUtils:119).

**Comment by kazoompa** [comment]
Is your user a `mica-user`? In our examples `mica-user` was set int the OIDC realm config.

**Comment by ymarcon** [comment]
The user is a user resulting from a (successful) OIDC signup.

**Comment by ymarcon** [comment]
Ok that was it: the user was created through signup from drupal, despite "mica-user" group was not specified in the OIDC realm configuration. So user can signup without being able to signin.

**Comment by ymarcon** [comment]
Then when an application is asking for the OIDC providers, only the ones having groups granting access to the requesting application should be returned. In my case I have defined a OIDC realm without groups so drupal should not have exposed the signup option to this realm.

**Comment by kazoompa** [comment]
Thus one must do the same for the other realms (jdbc, active directory and ldap) because they too are dependant on that default group

**Comment by meek0** [comment]
Tentative solution:
for signup, filter out all realms and providers where the realm does not have a default group or if that group exists, where that group can authenticate a user from the source application (e.g. signup from drupal then realms/providers must have a group that authorizes drupal).

**Comment by meek0** [comment]
I think we should also add a default application for a realm, so that a user from a delegated realm
 can login to Opal without being an administrator

**Comment by ymarcon** [comment]
Not sure I understand your reference to opal. Could you elaborate?

**Comment by kazoompa** [comment]
A registered user from a delegated realm wanting to login to Opal needs to be member of `opal-administrator` group which may not be desired. By only authorizing  Opal `application` without a group, the user can login as a normal user.

**Comment by ymarcon** [comment]
You are referring to the default setup only. One could make a group called potato in agate and give the appropriate permissions in opal for this group: no need to add a application field (using groups is more flexible and should be pushed).
