### ISSUE TITLE
OIDC Signin and Signup issues

### ISSUE THREAD

**Issue by ymarcon** [obiba/agate#397]
To reproduce the error:
* make a OIDC realm, make sure it is configured for an application
* do not check the Signup realm
* from application Signin with agate: the signin page does not show the OIDC realm

Then:
* go back to OIDC realm config and check Signup realm
* from application Signin with agate: the signin page shows the OIDC realm

**Comment by ymarcon** [comment]
I think I know why signup is needed:
* signup realm checked
* from application Signin with agate
* then Signin with the OIDC realm
* fill OIDC provider login form
* redirect to agate fails with a ugly error page:

![image](https://user-images.githubusercontent.com/2581149/62622401-8e5b0d00-b91e-11e9-8fb9-5f0a1c643ab6.png)

Instead of that agate should have redirect to the signup form (pre-filled): make user life easier, right now the exact procedure needs to be guessed.

**Comment by ymarcon** [comment]
FYI I am using Opal as the application, Agate as its ID provider. Then Agate delegates auth to KC (I have added a obiba-agate-local client to kc-staging). 

I expect the following:
* from opal, sign in with agate
* redirect to agate sign in
* sign in with KC
* redirect to agate (currently it stops here, which is not good)
* then redirect to opal

**Comment by kazoompa** [comment]
Opal Sign-In button must have a redirect URL to Opal otherwise Agate won't know where go once user is authenticated. Does the Opal Sign-In button have this query param?

**Comment by ymarcon** [comment]
Opal is applying standard OIDC. It works with other providers (elixir) that do auth delegation, just like agate. It's agate the problem.

**Comment by ymarcon** [comment]
Still not good:
* when Sign with agate from opal, the user is redirected to this page:
http://localhost:8081/#/login?response_type=code&client_id=opal&redirect_uri=http:%2F%2Flocalhost:8080%2Fauth%2Fcallback%2Fagate-localhost&scope=openid%20profile&state=1W5Jnx9t0qCqkPqQMtW2xUEYTjQCSQn7DDK_kv0xvSQ&redirect=%2Fauthorize
* but in the agate Sign in page, the link is http://localhost:8081/auth/signin/obiba-kc?redirect=http://localhost:8080

See the differences between the `redirect_uri` in the first link, and the `redirect` in the second one.

Then in the end, agate redirects to opal's main page, by-passing the opal's callback filter which means that opal is unable to complete the OIDC flow.

**Comment by ymarcon** [comment]
1. When user does not exist in Agate but has signed in successfully in a OIDC realm that allows signup, the user is correctly redirected to the signup form prefilled, but when signup is submitted the OIDC dance should be finalized (as the the user exists and has been signed in). Then a redirect to the authorize page with all the original OIDC parameters is expected.

2. When user does not exist in Agate but has signed in successfully in a OIDC realm that *does not allow signup*, the user is redirected to the default error page of the browser. Redirect to an appropriate Agate error page is expected.

![image](https://user-images.githubusercontent.com/2581149/62839728-956f7b80-bc8e-11e9-8cf5-1a52207ab90e.png)

**Comment by ymarcon** [comment]
When using drupal, the redirect to the signup page should be the drupal's one.
