### ISSUE TITLE
Cannot add a user in SQL or LDAP realm

### ISSUE THREAD

**Issue by ymarcon** [obiba/agate#417]
It is possible to directly add a user attached to agate default realm or to an OIDC realm but not to a SQL or a LDAP realm (assume AD is the same as LDAP).

**Comment by meek0** [comment]
The popup that appears when selecting the realm on signup is to authenticate the user before allowing the user to sign up to agate using that realm.

What do you mean by "directly add a user"?

**Comment by ymarcon** [comment]
I mean from Users page ("Add User" button) not from Signup page.
