### ISSUE TITLE
openid redirect to publicUrl

### ISSUE THREAD

**Issue by tdemalliard** [obiba/agate#427]
**Describe the bug**
Agate use publicUrl for openid authentification and redirect to it, but mica-drupal cannot handle it.

**To Reproduce**
1. agate : set public url to agate location
2. configure an openid identification with tier app, using agate 
3. openid work
4. agate : set public url to mica-drupal location
4. configure an openid identification with tier app, using mica-drupal url
3. openid fail
4. agate : set public url to mica-drupal location
4. configure an openid identification with tier app, using agate url 
3. openid fail with redirection to mica-drupal

**Expected behavior**
Openid works with agate publicURL set to mica-drupal application, or with an additionnal url for agate. PublicUrl must remain to mica-drupal for email links.

Openid urls are confirm to agate or mica-drupal by inspecting .well-known/openid-configuration.

**Desktop (please complete the following information):**
 - OS: debian 9 up to date
 - Browser chrome ubuntu 16.04 up to date
-  agate and mica-drupal up to date

**Comment by ymarcon** [comment]
I am not sure I understand: why both mica-drupal and the tier app are involved in the OIDC dance with agate? It should be only the tier-app and agate or mica-drupal and agate.

**Comment by ymarcon** [comment]
Is this because of this ?

> PublicUrl must remain to mica-drupal for email links

You can modify the email templates and hard-code the mica-drupal public URL instead of using the Agate's one.

**Comment by tdemalliard** [comment]
Exactly.

I have found the same solution : i am curretly modifying all the templates. But this is not a final solution as there could me additional templates with upcoming releases.

The tier app is there to verify that agate openid has validate the user and application.

**Comment by ymarcon** [comment]
Additional templates would not be an issue. It's the modification in a new release of a default one that would be identified by a packaging management system (such as dpkg or rpm).

**Comment by tdemalliard** [comment]
I have finished my docker migration, so I will not have this problem anymore. But if you add templates for the annual report, these will required to be modified manually.

I am thinking out loud: As I have altered templates, I need to track any template change and any new templates upon upgrading to a newer container.
