### ISSUE TITLE
Dedicated page for openid login

### ISSUE THREAD

**Issue by tdemalliard** [obiba/agate#428]
**Is your feature request related to a problem? Please describe.**
The user 1st login to openid is missing informations:
1. He arrive on a login page (agate) which could explain what is happening
2. Then he is prompt to autorize an application to access his data. This page is presenting a technical, not very user friendly.

**Describe the solution you'd like**
The login and autorise pages could be more user friendly.

**Comment by ymarcon** [comment]
This is the kind of page that is proposed by common ID providers such as Google etc. This is certainly not very friendly (and most likely no body reads it, like the Licenses or the Terms of Sales...). What do you propose?

**Comment by ymarcon** [comment]
Another option would be the ability to skip this step, according to the fact that the requesting application is a trusted one (Agate is not a self registering system for tier applications).

**Comment by tdemalliard** [comment]
That would be a great solution. All is on the same domain, the user should not be asked if he is ok with that.

**Comment by ymarcon** [comment]
Agreed, this is quite annoying for Opal too.

**Comment by ymarcon** [comment]
Agate automatically authorize one its application to get user profile information
