### ISSUE TITLE
agate default applications for new users

### ISSUE THREAD

**Issue by tdemalliard** [obiba/agate#429]
**Is your feature request related to a problem? Please describe.**
Users are allowed to access tier applications via openid with a specific application configured via the 'applications' config page of agate. 

Administrator has to add manually this openid application for every new users.

**Describe the solution you'd like**
An option to set automatic application membership for new users, like 'mica' and 'drupal' application are automatically set to every new users.

**Comment by ymarcon** [comment]
The sign up happens through Drupal, then it is possible to configure which groups are applied to the new users. Default is `mica-user` but it could be several other ones. And in Agate, for each of these groups, you can associate an application.

**Comment by tdemalliard** [comment]
Perfect.

**Comment by ymarcon** [comment]
Not so perfect... as I expect to get rid of Drupal soon. This signup configuration should be in the Mica configuration then.
What about the signup in Agate directly? are you using it for your tier app?

**Comment by tdemalliard** [comment]
The goal is to have a set of tier app accessible to the researchers who are registered : a genome browser and a data visualisation tool for aggregate data.

These tier apps require a login because the user has to accept some clauses during the sign up process.

**Comment by ymarcon** [comment]
I reopen this issue, to remember that the signup configuration should be in Mica's configuration.

**Comment by tdemalliard** [comment]
I did not completely answer: The signup could be done with agate. But if the user is already logged in, I expect the user to access the tier apps without a 2nd login. If the user is not already logged in, then it does not matter.

Maybe this can be achieved with a domain cookie:
1. the user login on drupal
1. cookie is set for the domain
1. user enter the tier app
1. tier app automatically redirect to agate
1. agate find that the user is already login via drupal due to the domain cookie (**unsure if this could be done with openid**)
1. user is automatically send back to the tier app

**Comment by ymarcon** [comment]
If the user has logged in Mica, the `obibaid` cookie is set for the domain (configured in Agate). But it is up to the tier app to validate this cookie against Agate and then start a new session for itself. That is how Mica and Opal work.
