### ISSUE TITLE
hide from user his groups, role and applications.

### ISSUE THREAD

**Issue by tdemalliard** [obiba/agate#434]
**Is your feature request related to a problem? Please describe.**
No problem is related to this feature.

**Describe the solution you'd like**
I would like to hide these informations (groups, role and applications) as it does not bring anything to the user.

These information should remain for the admin to see them.

This could also be applied to mica2. Mica2 display only groups and role.

**Describe alternatives you've considered**
I did not considered any solution.

**Additional context**
![image](https://user-images.githubusercontent.com/3911087/92128513-79c2a000-edd0-11ea-8e15-b7d21c0ffe4b.png)

**Comment by ymarcon** [comment]
Will make this configurable, default is not visible.
