### ISSUE TITLE
reset-password-proposal by administrator to new user fails

### ISSUE THREAD

**Issue by dmkuzsib** [obiba/agate#446]
Hi,

I am using Agate 2.2. 
If administrator proposes to reset [non-existing yet] password to new self-registered user via "Actions" menu on "Users" page, an error occurs. If password is beforehand set by administrator, a reset-password-proposal goes OK. 

Not sure if this is the feature, not a bug... IMHO useless for administrator to type in new password to be then reset by the user.

thanks,
Dmitry.

**Comment by kazoompa** [comment]
Hi,

Can you provide more information? Possibly the error in the
/var/log/agate/agate.log.

Normally, this action should result in an email sent to the user in
question, is your server setup properly for sending mails?

Best,

**Comment by dmkuzsib** [comment]
Hello,

My attempt to reset password ends up with a nice self-explaining note "Error!" on an otherwise empty page with Agate theme. Zero records in agate.log

Emailing is, of course, configured on the server and does deliver messages, e.g. when new user is self-registered or the user's [previously set by administrator] password is reset. 
thanks,
Dmitry.
![image](https://user-images.githubusercontent.com/18529415/118480677-dd002280-b712-11eb-81fc-1527a7f08f14.png)

**Comment by kazoompa** [comment]
The reason for the error is that user status is in pending and the resetPassword fails as the server cannot find any credentials for the new user and an exception is thrown: 

`if(userCredentials == null) throw new BadRequestException("User has no defined credentials.");`

We could send a better error message or as in Mica, have a configuration in Agate to let the newly registered user assign a password.

**Comment by dmkuzsib** [comment]
> have a configuration in Agate to let the newly registered user assign a password.
yes

or just let user type a password while self-registering

**Comment by kazoompa** [comment]
This issue is no longer reproducible with the the fix in #450, the password reset button won't show when a user's status is **not active**.

**Comment by dmkuzsib** [comment]
Does changing user status from Pending to Active also assigns user a temporary password, or administrator still should type in one? 
IMHO useless to assign an unknown to user password without means to communicate it to the user. Assigning a random one is a better option.

**Comment by kazoompa** [comment]
Reset password sends an email to the user for a password input.
