### ISSUE TITLE
[2.3.0] Proxy ip is logged instant the original one.

### ISSUE THREAD

**Issue by tuxmaster5000** [obiba/agate#455]
When agate runs behind an apache which is run as an reverse proxy, the wrong ip is logged.
Sample:

> org.obiba.agate.web.rest.security.SessionsResource - Authentication failure of user 'foo' at ip: '127.0.0.1': Authentication failed for token submission [org.apache.shiro.authc.UsernamePasswordToken - foo, rememberMe=false].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).

The correct use will logged, but not the ip of the client. Only the ip of the proxy server will logged.

**Comment by ymarcon** [comment]
Do you have the correct IP in the rest.log file?

**Comment by tuxmaster5000** [comment]
Yes in the rest.log, the correct one is logged. And in the agate.log the wrong one is logged.
