### ISSUE TITLE
[2.5.0] systemd service file broken

### ISSUE THREAD

**Issue by mdc-webdb** [obiba/agate#471]
After the update to 2.5.0 agate don't start anymore on CentIOS8, because the systemd service file is broken,
 /usr/lib/systemd/system/agate.service:15: Executable "$JAVA" not found in path "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"

**Comment by mdc-webdb** [comment]
As workaround:
cat /etc/systemd/system/agate.service.d/472.conf
[Service]
Type=forking
ExecStart=
ExecStart=/usr/share/agate/bin/agate.sh

**Comment by ymarcon** [comment]
For some reason the migration to systemd was not finalized... Thanks for the report, please try with agate 2.5.1.

**Comment by ymarcon** [comment]
Fixed too quickly... Tested successfully with 2.5.2.
