### ISSUE TITLE
[2.5.4] Unable to set the listen address for the https connector. 

### ISSUE THREAD

**Issue by tuxmaster5000** [obiba/agate#477]
For the http connection it will be possible to set the port and the listen address.
But for the https connection, only the port can set. This will result in the fact, that the https connector will listen on 0.0.0.0.

It will be better to allow also to set an listen address for the https connector. And for example, when agate runs behind an local reverse proxy, then it will be an good idea to add an option disable the https connector, because the tls termination is done by the proxy in front of agate.

**Comment by ymarcon** [comment]
Doesn't `server.address` property apply to both http and https?

**Comment by tuxmaster5000** [comment]
No, this was my first idea. It will only work  for the http connector.
My settings:
```
server:
    port: 8080
    address: 127.0.0.1
```
which will result in:

> 2022-02-23 10:27:21,530 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@9f2fe2e{HTTP/1.1, (http/1.1)}{127.0.0.1:8080}
> 2022-02-23 10:27:21,644 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@5abc5854{SSL, (ssl, http/1.1)}{0.0.0.0:8444}

When I set:
```
https:
   port: 8442
```
for example this will only result in:

> org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@5abc5854{SSL, (ssl, http/1.1)}{0.0.0.0:8442}

And add an second address entry to the https section don't have any result.

**Comment by ymarcon** [comment]
Please have a try with [Agate 2.5.5](https://github.com/obiba/agate/releases/tag/2.5.5)

**Comment by tuxmaster5000** [comment]
Yes this will works. Thanks:

> 2022-02-23 14:14:42,484 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@1280bae3{HTTP/1.1, (http/1.1)}{127.0.0.1:8080}
> 2022-02-23 14:14:42,618 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@3d7b3b18{SSL, (ssl, http/1.1)}{127.0.0.1:8444}
>
