### ISSUE TITLE
Tenable Scan Warning - Password Field With Auto-Complete 

### ISSUE THREAD

**Issue by jonathanmasseurca** [obiba/agate#501]
![image](https://user-images.githubusercontent.com/49443479/214082589-46b01a74-c0b1-44d3-93e4-44e78882e6e6.png)

**Comment by jonathanmasseurca** [comment]
Agate version 2.7.4.
Mica version 5.0.3

The same security warning appear for mica.

Hope this help,

**Comment by jonathanmasseurca** [comment]
@ymarcon  I investigated a little bit, we just need to add the html tag  << autocomplete="new-password" >> to the password box and it will remove this warning.

**Comment by ymarcon** [comment]
`"off"` is more appropriate: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values

This is a low security warning. I would suggest that you override override the `signin.ftl` file instead. See doc:
* https://agatedoc.obiba.org/en/latest/admin/pub-configuration.html
* https://micadoc.obiba.org/en/latest/admin/pub-configuration.html
