### ISSUE TITLE
Tenable Scan Warning - Blind NoSQL Injection (differential analysis)

### ISSUE THREAD

**Issue by jonathanmasseurca** [obiba/agate#502]
![image](https://user-images.githubusercontent.com/49443479/214084615-7ba58549-50ff-4525-99a0-077ca11170a0.png)

**Comment by ymarcon** [comment]
Please provide an example with curl.

**Comment by jonathanmasseurca** [comment]
I investigated more in details.

I think it's a false positive because the web page is displaying Authentication failed. Please verify credentials. with the same parameters.

I think maybe it's because it's receive an HTTP 200 and the scanner think it worked.

I will close this ticket because I don't think there is an issue there.

**Comment by jonathanmasseurca** [comment]
Many thanks @ymarcon
