### ISSUE TITLE
Ubuntu 22.04 - repo - key expired

### ISSUE THREAD

**Issue by jonathanmasseurca** [obiba/agate#513]
Hi,

One of my collegue pointed out that the apt-key is expired.

I tried to redownload the latest key but it's still the same 

![image](https://user-images.githubusercontent.com/49443479/220136526-2affcb41-3c9f-42b6-8907-90122c7cbab2.png)

![image](https://user-images.githubusercontent.com/49443479/220136899-539da060-4091-4520-86ab-96d40bfbf197.png)

Thank you for your help,

**Comment by ymarcon** [comment]
It should be ok now, could you verify?

**Comment by ymarcon** [comment]
By the way, I have updated the [deb instructions](https://www.obiba.org/pages/pkg/) (no more deprecated apt-key):

```
curl -fsSL https://www.obiba.org/assets/obiba-pub.pem | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/obiba.gpg
```

**Comment by thiagomdiniz** [comment]
Hi, 
thanks for the support!

Now it's OK. Steps I performed:

View expired key:

`sudo apt-key list`

```
pub   rsa3072 2021-02-16 [SC] [expired: 2023-02-16]
      0E52 FB02 F890 D305 8B6C  964D 8576 AC15 7B0A 831B
uid           [ expired] Yannick Marcon <yannick.marcon@obiba.org>
```

Delete expired key:

`sudo apt-key del 7B0A831B`

Import new key:

```
curl -fsSL https://www.obiba.org/assets/obiba-pub.pem | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/obiba.gpg
```

I needed to update the APT list file.
It was like this:

```
cat /etc/apt/sources.list.d/obiba.list 
deb [arch=amd64 signed-by=/usr/share/keyrings/obiba.gpg] https://obiba.jfrog.io/artifactory/debian-local all main
```

I left it like that:

```
cat /etc/apt/sources.list.d/obiba.list 
deb https://obiba.jfrog.io/artifactory/debian-local all main
```

And so `apt-get update` worked.

Thank you!!

**Comment by ymarcon** [comment]
Thanks for the report.
