### ISSUE TITLE
TLS 1.2 handshake doesnt work on JavaMailSenderImpl 

### ISSUE THREAD

**Issue by massej** [obiba/agate#517]
**Describe the bug**
TLS 1.2 handshake doesnt work on JavaMailSenderImpl on port 587.

Error : 
![image](https://github.com/obiba/agate/assets/22155257/827f119e-17e2-48d5-8f7c-2994d1db225d)

Use a TLS mail server that require at least TLS 1.2.

There is a missing  property that need to be set : props.put("mail.smtp.ssl.protocols", "TLSv1.2");

**Comment by jonathanmasseurca** [comment]
See file : https://github.com/obiba/agate/blob/b6463f73e0bb69c354af8d1bf6b46ec696d677ae/agate-core/src/main/java/org/obiba/agate/config/MailConfiguration.java#L42

**Comment by ymarcon** [comment]
Isn't it something that you can pass in the JAVA_OPTS?

`... -Dmail.smtp.ssl.protocols=TLSv1.2 ...`

Note: `PROP_TLS` is for extracting the `spring.mail.tls` property, which value is a logical.

**Comment by massej** [comment]
I installed a postfix relay instead, postfix can make the tls connection and agate is able to connect locally on postfix.

**Comment by massej** [comment]
I forgot to add in the spring.log I also have this 

javax.mail.AuthenticationFailedException: 421 4.7.66 TLS 1.0 and 1.1 are not supported. Please upgrade/update your client to support TLS 1.2

**Comment by massej** [comment]
https://stackoverflow.com/questions/47166425/how-to-force-javamailsenderimpl-to-use-tls1-2

Alot of people have the same issue

`returned as an SMTP error by some Microsoft mail server) and didn't go away with 1.5.0-b01; but upgrading to latest available (com.sun.mail:javax-mail:1.6.2) along with the session property, seemed to resolve the issue`

We are also using a Microsoft mail server, and when I check the current agate version 2.8.0 of the mailx it is 1.5.0-b01.

I think we just need to update the mailx-mail client to at least 1.6 and it will support TLS 1.2.

**Comment by meek0** [comment]
Hi, a new `snapshot` image is available for testing with your setup.
It uses new `javax.mail` version (1.6.2) and explicitly sets mail ssl protocol to tls1.2
