### ISSUE TITLE
Bug - Username with space issue

### ISSUE THREAD

**Issue by massej** [obiba/agate#521]
**Describe the bug**
When a user create a username with a space, it create issue with mica.

**To Reproduce**

Create a username with a space at the end.

**Expected behavior**
The space should be trimmed or removed on creation.

**Screenshots**
<img width="562" alt="image" src="https://github.com/obiba/agate/assets/22155257/15d4ceeb-a546-4086-9026-0e338c234f33">

In mica the association doesnt work (only username and fullname is showed without the lastname (the lastname is lost))
<img width="1206" alt="image" src="https://github.com/obiba/agate/assets/22155257/9e74acde-2813-474d-87dc-564ad7d373b4">

Here is a working example : (You also have all the user info in mica)
<img width="605" alt="image" src="https://github.com/obiba/agate/assets/22155257/a9d4adc4-3d2f-4187-9bde-7aa201e3e70a">

The user cannot do amendement due to this line 
https://github.com/obiba/mica2/blob/9b26a7adef5a185b85f3a43c5cf5aef725fe13a8/mica-webapp/src/main/resources/_templates/libs/data-access-sidebar.ftl#L141

<#if feasibilities?size != 0 || user.username == dar.applicant || isAdministrator>

it compare the username with a space and dar.applicant without space and cause issue.

Thank you for your help,

**Comment by ymarcon** [comment]
Fixed and released (includes an automated upgrade step that will trim the user names and emails if necessary) , thanks for the report.

**Comment by massej** [comment]
Thank you @ymarcon you're the best!
